import * as T from './three.module.js';
const $=s=>document.querySelector(s), canvas=$('#world');
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('#start').textContent='3D is unavailable in this browser';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0xa9def0);
const scene=new T.Scene();scene.fog=new T.Fog(0xa9def0,100,235);const camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,350);
scene.add(new T.HemisphereLight(0xd8f6ff,0x67935b,2.3));const sun=new T.DirectionalLight(0xfff2d4,2.6);sun.position.set(-45,85,35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-95,right:95,top:95,bottom:-95,far:220});sun.shadow.bias=-.0005;scene.add(sun);
const mats=new Map(), boxes=[], stars=[], crates=[], anchors=[], bots=[], particles=[], pads=[];
function mat(c){if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.85}));return mats.get(c);}
function box(x,y,z,w,h,d,c,solid=false){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(x,y+h/2,z);m.castShadow=h>1;m.receiveShadow=true;scene.add(m);if(solid)boxes.push({x,z,w,d,top:y+h,bottom:y});return m;}
function ball(x,y,z,r,c){const m=new T.Mesh(new T.IcosahedronGeometry(r,1),mat(c));m.position.set(x,y,z);m.castShadow=true;scene.add(m);return m;}
function label(text,x,y,z,color='#214652',scale=1){let c=document.createElement('canvas');c.width=512;c.height=96;let ctx=c.getContext('2d');ctx.fillStyle='#fff8e6';ctx.beginPath();ctx.roundRect(0,0,512,96,20);ctx.fill();ctx.fillStyle=color;ctx.font='bold 35px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,60);let m=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c)}));m.position.set(x,y,z);m.scale.set(14*scale,2.63*scale,1);scene.add(m);return m;}
function tree(x,z,s=1){box(x,0,z,.8*s,3*s,.8*s,0x946c48);ball(x,4*s,z,2.1*s,0x4baf72);ball(x+.8*s,5*s,z,.95*s,0x76c578);}
function ring(x,y,z){const m=new T.Mesh(new T.TorusGeometry(1,.19,6,16),mat(0x4ff2ff));m.position.set(x,y,z);scene.add(m);anchors.push(m);return m;}
function star(x,y,z){let m=new T.Mesh(new T.OctahedronGeometry(.65),new T.MeshStandardMaterial({color:0xffce35,emissive:0xc88512,emissiveIntensity:.35,metalness:.2,roughness:.3}));m.position.set(x,y,z);scene.add(m);stars.push({m,id:stars.length,y});}
function crate(x,z,type){let m=box(x,0,z,2.4,2.4,2.4,[0,0x29bfe6,0xff866e,0xc197ff][type]);box(x,1,z,2.6,.4,2.6,0xfff2c9);label(['','GRAPPLE HOOK','BUBBLE BLASTER','SUPER BOUNCE'][type],x,5,z,'#214652',.7);crates.push({m,x,z,type});}
// A compact continuous world, with recognizable landmarks and short paths.
box(0,-2,0,190,2,190,0x8fcf89);box(0,-3,0,210,1,210,0x55c3d5);
box(0,0,0,22,.08,184,0x70888e);box(0,0,0,184,.08,18,0x70888e);
box(-13,0,0,3,.16,184,0xd9ddd0);box(13,0,0,3,.16,184,0xd9ddd0);box(0,0,-11,184,.16,3,0xd9ddd0);box(0,0,11,184,.16,3,0xd9ddd0);
for(let i=-85;i<90;i+=10){if(Math.abs(i)>13){box(0,.09,i,.3,.01,4,0xffedac);box(i,.09,0,4,.01,.3,0xffedac);}}
// Fountain square and colorful city blocks.
box(27,0,28,29,.2,28,0xe5d9b5);box(27,.2,29,10,.8,10,0xfff3d8,true);box(27,1,29,8,.12,8,0x46c6e4);box(27,1.1,29,2,2.2,2,0xf7edcd,true);ball(27,3.7,29,.85,0x6de0ec);
label('SUNSHINE SQUARE',24,10,46,'#307f72',1);
const colors=[0xf3b258,0xe78978,0x72b9c7,0xa797cd,0xedd17b];let bi=0;
for(const [x,z,w,d,h]of [[-27,24,16,14,13],[-47,24,14,16,20],[-68,25,16,17,12],[-27,48,16,15,24],[-49,50,15,14,16],[-69,52,16,14,30],[49,24,13,16,12],[67,26,14,17,19],[48,51,16,17,23],[69,52,14,14,13]]){const c=colors[bi++%5];box(x,0,z,w,h,d,c,true);box(x,h,z,w+1,.6,d+1,0xfff4d7,true);for(let floor=3;floor<h-1;floor+=4)for(let a=-w/2+2;a<w/2-1;a+=3.5){box(x+a,floor,z-d/2-.04,1.5,2,.15,0x355868);box(x+a,floor,z+d/2+.04,1.5,2,.15,0x355868);}box(x,0,z-d/2-.2,3,3.6,.5,0x325467);ring(x,h+3,z);star(x,h+1.6,z+3);}
label('ROOFTOP CLUB',-69,34,52,'#8162b6',.8);
// Park and friendly target robots.
box(-47,.01,-48,67,.1,64,0x6ebd82);box(-47,.12,-48,56,.08,4,0xe5d7ad);box(-47,.12,-48,4,.08,56,0xe5d7ad);label('BOTANICAL BOT PARK',-45,10,-18,'#308461',1);
for(let i=0;i<12;i++){let x=-77+(i%4)*19,z=-73+Math.floor(i/4)*22;if(Math.abs(x+47)>8)tree(x,z,1+(i%3)*.18);}
function makeBot(x,z){const g=new T.Group();function part(w,h,d,c,px,py,pz){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(px,py,pz);m.castShadow=true;g.add(m);}part(2,1.7,1.5,0xffb877,0,1.5,0);part(2.3,1.6,1.7,0x9bddcd,0,3.1,0);part(.4,.4,.1,0x214b59,-.55,3.3,.89);part(.4,.4,.1,0x214b59,.55,3.3,.89);part(.65,.8,.65,0x34586a,-.6,.4,0);part(.65,.8,.65,0x34586a,.6,.4,0);g.position.set(x,0,z);scene.add(g);bots.push({g,x,z,cool:0,hits:0});}
for(const [x,z]of [[-35,-34],[-61,-49],[-32,-66],[-65,-70],[-55,-27]])makeBot(x,z);
// Beach and pier.
box(49,0,-42,65,.13,62,0xf3db97);box(58,.01,-77,75,.16,22,0x54c8db);box(48,.3,-70,8,.7,32,0xb99064,true);box(48,.3,-85,24,.7,7,0xb99064,true);label('BUBBLE BEACH',44,10,-18,'#25899c',.95);
for(let i=0;i<5;i++){let x=24+i*13,z=-33-(i%2)*21;box(x,.15,z,.35,4,.35,0x946d4a);const roof=new T.Mesh(new T.ConeGeometry(3.3,1.3,8),mat(i%2?0xe98480:0x6fc2c0));roof.position.set(x,4.5,z);scene.add(roof);box(x+2,.13,z+1,1.5,.4,3,0xfff6d5);}
// Mountain stepping trail and launch pads.
box(0,.1,76,28,3,25,0x9dad82,true);box(0,3.1,81,19,4,16,0xadb696,true);box(0,7.1,85,11,5,9,0xc3c6a9,true);ring(0,16,85);star(0,13.5,85);label('SKYHOP HILL',1,21,86,'#777652',.8);
for(const [x,z]of [[20,65],[-18,70],[0,64],[-45,74],[65,75]]){let m=box(x,.05,z,4,.35,4,0xb586ee);pads.push({x,z,m});ring(x,5,z);}
for(let i=0;i<16;i++){let x=-83+(i%8)*23,z=i<8?86:-87;if(Math.abs(x)>17)tree(x,z,1.1);}
crate(20,17,1);crate(-23,-22,2);crate(27,-60,3);
for(const [x,z]of [[17,12],[19,15],[24,21],[34,34],[37,44],[-18,12],[-36,12],[-59,12],[-19,-17],[-26,-26],[-44,-47],[-69,-50],[-33,-66],[22,-18],[35,-38],[63,-53],[48,-65],[48,-83],[0,55],[-18,67],[64,74]])star(x,1.7,z);
// Clouds beyond the island.
for(let i=0;i<12;i++){let x=Math.sin(i*2.4)*115,z=Math.cos(i*2.4)*115;for(let j=0;j<3;j++)box(x+j*5,42+(i%4)*5,z,9,3+j%2*2,6,0xffffff);}
// Blocky explorer, intentionally readable at a distance.
const player=new T.Group();scene.add(player);function limb(w,h,d,c,x,y,z){let m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;player.add(m);return m;}
limb(1.35,1.35,.8,0xf5b943,0,1.8,0);limb(1.15,1.1,1.05,0xf3cf9c,0,3,0);limb(1.3,.32,1.15,0x326a78,0,3.65,0);limb(1.4,.12,.5,0x326a78,0,3.54,.5);limb(.16,.16,.05,0x273f49,-.25,3.1,.55);limb(.16,.16,.05,0x273f49,.25,3.1,.55);limb(.62,.8,.4,0xe77e4e,0,1.8,-.54);const legs=[limb(.49,.95,.6,0x3b677b,-.37,.53,0),limb(.49,.95,.6,0x3b677b,.37,.53,0)],arms=[limb(.43,1.15,.57,0xf3cf9c,-.9,1.9,0),limb(.43,1.15,.57,0xF3cf9c,.9,1.9,0)];player.position.set(14,0,5);
let saved={};try{saved=JSON.parse(localStorage.getItem('pocketCity-v1')||'{}')||{};}catch{}const unlocked=new Set([0,...(Array.isArray(saved.tools)?saved.tools.filter(n=>[1,2,3].includes(n)):[])]), collected=new Set(Array.isArray(saved.stars)?saved.stars.filter(n=>Number.isInteger(n)&&n>=0&&n<stars.length):[]), visited=new Set(Array.isArray(saved.areas)?saved.areas.filter(n=>n>=0&&n<4):[]);let botHits=Number.isFinite(saved.hits)?Math.max(0,saved.hits):0;
for(const s of stars)if(collected.has(s.id))s.m.visible=false;for(const c of crates)if(unlocked.has(c.type))c.m.visible=false;
let tool=0,active=false,paused=false,yaw=Math.PI*.8,pitch=.32,vy=0,onGround=true,clock=new T.Clock(),time=0,actionCooldown=0,grapple=null,drag=null,toastTimer,joystick={x:0,y:0},sound=false,audio;
const keys={};let rope=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:0x42eaff}));scene.add(rope);rope.visible=false;
function save(){try{localStorage.setItem('pocketCity-v1',JSON.stringify({tools:[...unlocked],stars:[...collected],areas:[...visited],hits:botHits}));}catch{}}
function tone(f=600){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.18);}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function ui(){ $('#stars').textContent=collected.size;$('#progress').style.width=visited.size/4*100+'%';$('#progressText').textContent=visited.size+' of 4 neighborhoods explored';document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('unlocked',unlocked.has(+b.dataset.tool));b.classList.toggle('selected',+b.dataset.tool===tool);});if(!unlocked.has(1)){$('#questTitle').textContent='Follow the golden stars';$('#questText').textContent='Find the blue gadget crate near the fountain.';}else if(!unlocked.has(2)){$('#questTitle').textContent='Meet the park robots';$('#questText').textContent='Head across the road to the green park. An orange crate is waiting!';}else if(!unlocked.has(3)){$('#questTitle').textContent='A beachside surprise';$('#questText').textContent='Find the purple crate beside the beach umbrellas.';}else if(visited.size<4){$('#questTitle').textContent='Take the high road';$('#questText').textContent='Try your bounce gadget at Skyhop Hill, beyond the city.';}else{$('#questTitle').textContent=collected.size===stars.length?'You’re a city superstar!':'The rooftop star hunt';$('#questText').textContent=collected.size===stars.length?'Every star found! Keep bouncing, grappling, and playing.':`${stars.length-collected.size} stars left to discover. Grapple to the rooftops!`;}}
function select(n){if(!unlocked.has(n)){toast(['','Find the blue crate by the fountain','Find the orange crate at the park','Find the purple crate at the beach'][n]);return;}tool=n;ui();$('#tip').textContent=['WASD / arrows to move · Drag to look · Space to jump','Aim at a blue ring · Click / E to grapple · Space to let go','Face a nearby robot · Click / E to send a bubble','Click / E for a super bounce · Steer while in the air'][n];}
function burst(pos,color){for(let i=0;i<12;i++){let m=ball(pos.x,pos.y+1,pos.z,.16,color);particles.push({m,v:new T.Vector3((Math.random()-.5)*9,Math.random()*8,(Math.random()-.5)*9),life:.8});}}
function chooseAnchor(){let best=null,score=1e9;for(const a of anchors){let d=a.position.distanceTo(player.position);if(d>65||d<3)continue;const p=a.position.clone().project(camera);let s=Math.hypot(p.x,p.y);if(p.z<1&&s<.7&&s<score){best=a;score=s;}}return best;}
function jump(){if(!active||paused)return;if(grapple){grapple=null;vy=8;}else if(onGround){vy=12;onGround=false;tone(350);}}
function use(){if(!active||paused||actionCooldown>0)return;actionCooldown=.35;if(tool===0){toast('Choose a gadget below, or follow the stars to find one!');return;}if(tool===1){let a=chooseAnchor();if(a){grapple=a.position.clone();vy=0;tone(750);}else toast('Look toward a blue ring, then use your grapple.');}if(tool===2){let target=null,best=28;const forward=new T.Vector3(Math.sin(yaw),0,Math.cos(yaw)).negate();for(const b of bots){const v=b.g.position.clone().sub(player.position);const d=v.length();if(b.cool<=0&&d<best&&v.normalize().dot(forward)>.4){target=b;best=d;}}const start=player.position.clone().add(new T.Vector3(0,2.5,0)),end=target?target.g.position.clone().add(new T.Vector3(0,2,0)):start.clone().addScaledVector(forward,25);const m=ball(start.x,start.y,start.z,.55,0x89eaff);particles.push({m,v:end.sub(start).normalize().multiplyScalar(35),life:best/35,hit:target});tone(480);}if(tool===3){if(onGround){vy=25;onGround=false;burst(player.position,0xc394ff);tone(820);}else toast('Land first, then bounce again!');}}
function setPause(p){paused=p;$('#menu').hidden=!p;Object.keys(keys).forEach(k=>delete keys[k]);joystick={x:0,y:0};$('#thumb').style.transform='';drag=null;}
$('#start').onclick=()=>{active=true;document.body.classList.add('playing');yaw=Math.PI;pitch=.28;toast('Walk into the blue crate to get your first gadget!');};$('#pause').onclick=()=>{if(active)setPause(true);};$('#resume').onclick=()=>setPause(false);$('#home').onclick=()=>{player.position.set(14,0,5);vy=0;grapple=null;setPause(false);toast('Back at Sunshine Square');};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='Sound: '+(sound?'on':'off');tone();};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>select(+b.dataset.tool));$('#jump').onpointerdown=e=>{e.preventDefault();jump();};$('#use').onpointerdown=e=>{e.preventDefault();use();};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys[e.code]=true;if(e.code==='Space')jump();if(e.code==='KeyE')use();if(e.code==='Escape'&&active)setPause(!paused);if(/^Digit[1-4]$/.test(e.code))select(+e.code.slice(-1)-1);});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{if(active)setPause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)setPause(true);});
canvas.onpointerdown=e=>{if(!active||paused)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,move:0};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.move+=Math.abs(dx)+Math.abs(dy);yaw-=dx*.006;pitch=Math.max(-.12,Math.min(1.1,pitch+dy*.005));drag.x=e.clientX;drag.y=e.clientY;};canvas.onpointerup=e=>{if(drag&&drag.id===e.pointerId){if(drag.move<8)use();drag=null;}};canvas.onpointercancel=()=>drag=null;
const stick=$('#stick');let stickId=null;function moveStick(e){let r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/40,y=(e.clientY-r.top-r.height/2)/40,len=Math.max(1,Math.hypot(x,y));joystick={x:x/len,y:y/len};$('#thumb').style.transform=`translate(${joystick.x*30}px,${joystick.y*30}px)`;}stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);};stick.onpointermove=e=>{if(e.pointerId===stickId)moveStick(e);};function stopStick(){stickId=null;joystick={x:0,y:0};$('#thumb').style.transform='';}stick.onpointerup=stopStick;stick.onpointercancel=stopStick;
function floorAt(x,z,oldY,newY){let floor=0;for(const b of boxes)if(Math.abs(x-b.x)<b.w/2+.48&&Math.abs(z-b.z)<b.d/2+.48&&oldY>=b.top-.12&&newY<=b.top)floor=Math.max(floor,b.top);return floor;}
function moveAxis(axis,amount){let next=player.position[axis]+amount;let x=axis==='x'?next:player.position.x,z=axis==='z'?next:player.position.z;for(const b of boxes)if(player.position.y<b.top-.1&&player.position.y+3.5>b.bottom+.1&&Math.abs(x-b.x)<b.w/2+.6&&Math.abs(z-b.z)<b.d/2+.6)return;player.position[axis]=next;}
const names=['Sunshine Square','Botanical Bot Park','Bubble Beach','Skyhop Hill'];let currentArea=-1;
function update(dt){time+=dt;actionCooldown=Math.max(0,actionCooldown-dt);let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joystick.x,z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+joystick.y;const len=Math.max(1,Math.hypot(x,z));x/=len;z/=len;let vx=(Math.cos(yaw)*x+Math.sin(yaw)*z)*11,vz=(-Math.sin(yaw)*x+Math.cos(yaw)*z)*11;
if(grapple){const dir=grapple.clone().sub(player.position).add(new T.Vector3(0,1,0));const distance=dir.length();if(distance<1){player.position.copy(grapple).add(new T.Vector3(0,1,0));grapple=null;vy=2;}else{player.position.addScaledVector(dir.normalize(),Math.min(38*dt,distance));onGround=false;}}else{moveAxis('x',vx*dt);moveAxis('z',vz*dt);let oldY=player.position.y;vy-=26*dt;let newY=oldY+vy*dt,floor=floorAt(player.position.x,player.position.z,oldY,newY);if(newY<=floor&&vy<=0){player.position.y=floor;vy=0;onGround=true;}else{player.position.y=newY;onGround=false;}}
if(Math.hypot(vx,vz)>.1){player.rotation.y=Math.atan2(vx,vz);legs[0].rotation.x=Math.sin(time*13)*.55;legs[1].rotation.x=-legs[0].rotation.x;arms[0].rotation.x=-legs[0].rotation.x;arms[1].rotation.x=legs[0].rotation.x;}else{legs.forEach(l=>l.rotation.x=0);arms.forEach(l=>l.rotation.x=0);}
if(Math.abs(player.position.x)>94||Math.abs(player.position.z)>94||player.position.y<-8){player.position.set(14,0,5);vy=0;grapple=null;toast('Splash! Back to the fountain.');}
let area=player.position.z>62?3:player.position.z<-14?(player.position.x<0?1:2):0;if(area!==currentArea){currentArea=area;$('#area').textContent=names[area];if(!visited.has(area)){visited.add(area);ui();save();if(visited.size>1)toast('Discovered '+names[area]+'!');}}
for(const s of stars){if(collected.has(s.id))continue;s.m.rotation.y=time*1.7;s.m.position.y=s.y+Math.sin(time*2+s.id)*.18;if(s.m.position.distanceTo(player.position.clone().add(new T.Vector3(0,1.5,0)))<2){collected.add(s.id);s.m.visible=false;burst(s.m.position,0xffda45);tone(700+collected.size*10);ui();save();if(collected.size===stars.length)toast('★ All 32 stars! You’re a Pocket City superstar!');}}
for(const c of crates){if(unlocked.has(c.type))continue;c.m.rotation.y=Math.sin(time)*.15;if(Math.hypot(player.position.x-c.x,player.position.z-c.z)<3&&player.position.y<4){unlocked.add(c.type);c.m.visible=false;select(c.type);save();burst(player.position,0x69ddec);toast(['','Grapple found! Aim at a blue ring and press USE.','Bubble blaster found! Face a robot and press USE.','Super bounce found! Press USE for a giant jump.'][c.type]);tone(950);}}
for(const p of pads)if(onGround&&Math.hypot(player.position.x-p.x,player.position.z-p.z)<2){vy=25;onGround=false;tone(850);}
for(const b of bots){b.cool=Math.max(0,b.cool-dt);b.g.rotation.y=Math.sin(time*.7+b.x)*.5;b.g.position.y=b.cool>0?1+Math.sin(time*5)*.6:Math.abs(Math.sin(time*2+b.x))*.12;b.g.rotation.z=b.cool>0?Math.sin(time*8)*.15:0;}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.m.position.addScaledVector(p.v,dt);if(!p.hit)p.v.y-=12*dt;if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();if(p.hit&&p.hit.cool<=0){p.hit.cool=4;botHits++;burst(p.hit.g.position,0x6aeee5);tone(1000);toast(botHits===1?'Nice shot! The robots love a bubble dance.':`${botHits} bubble dances!`);save();}particles.splice(i,1);}}
}
function drawMap(){const c=$('#map').getContext('2d'),scale=.76,center=84;c.fillStyle='#b2d29b';c.fillRect(0,0,168,168);c.fillStyle='#77b98e';c.fillRect(12,12,60,60);c.fillStyle='#eed49a';c.fillRect(96,12,60,60);c.fillStyle='#899996';c.fillRect(76,0,16,168);c.fillRect(0,77,168,14);c.fillStyle='#fff0cf';for(const b of boxes)if(b.top>5){c.fillRect(center+b.x*scale-b.w*scale/2,center+b.z*scale-b.d*scale/2,b.w*scale,b.d*scale);}for(const cr of crates)if(!unlocked.has(cr.type)){c.fillStyle=['','#21bde5','#f48164','#b189e1'][cr.type];c.fillRect(center+cr.x*scale-3,center+cr.z*scale-3,7,7);}c.fillStyle='#e8a92b';for(const s of stars)if(!collected.has(s.id)){c.beginPath();c.arc(center+s.m.position.x*scale,center+s.m.position.z*scale,1.6,0,7);c.fill();}c.save();c.translate(center+player.position.x*scale,center+player.position.z*scale);c.rotate(-yaw);c.fillStyle='#1b4356';c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(0,3);c.lineTo(-5,5);c.closePath();c.fill();c.restore();}
function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.035);if(active&&!paused)update(dt);else if(!active)yaw+=dt*.045;const target=player.position.clone().add(new T.Vector3(0,2,0));const dist=innerWidth<650?16:19;let offset=new T.Vector3(Math.sin(yaw)*Math.cos(pitch)*dist,Math.sin(pitch)*dist+5,Math.cos(yaw)*Math.cos(pitch)*dist);const ray=new T.Ray(target,offset.clone().normalize());let distance=offset.length();for(const b of boxes){const bounds=new T.Box3(new T.Vector3(b.x-b.w/2-.2,b.bottom,b.z-b.d/2-.2),new T.Vector3(b.x+b.w/2+.2,b.top+.2,b.z+b.d/2+.2));const hit=ray.intersectBox(bounds,new T.Vector3());if(hit)distance=Math.min(distance,Math.max(1.5,hit.distanceTo(target)-.5));}camera.position.copy(target).addScaledVector(offset.normalize(),distance);camera.lookAt(target);
for(const b of anchors){b.rotation.y=time*.4;}rope.visible=!!grapple;if(grapple){rope.geometry.setFromPoints([player.position.clone().add(new T.Vector3(0,2,0)),grapple]);}
const a=tool===1&&active&&!paused?chooseAnchor():null;$('#aim').style.color=a?'#59ffff':'white';$('#targetHint').style.display=active&&!paused&&tool!==0?'block':'none';$('#targetHint').textContent=tool===1?(a?'✦ Grapple ready · Click / E / USE':'Aim at a glowing blue ring'):tool===2?'Face a robot · Click / E / USE':'Super jump · Click / E / USE';drawMap();renderer.render(scene,camera);}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});ui();$('#start').disabled=false;$('#start').textContent='Let’s explore  →';render();
